const actions = {
  LOADING: 'LOADING',
  DONE_LOADING: 'DONE_LOADING',
  LOADING_SUBMIT: 'LOADING_SUBMIT',
  DONE_LOADING_SUBMIT: 'DONE_LOADING_SUBMIT',

  //PETUGAS
  LIST_PETUGAS: 'LIST_PETUGAS',
  DETAIL_PETUGAS: 'DETAIL_PETUGAS',

  //PENGADUAN
  LIST_PENGADUAN: 'LIST_PENGADUAN',
};

export default actions;
